[[languages.cpp.environments]]
CXX = "g++-12"
CXXFLAGS = ["-O2", "-std=c++2b", "-I/opt/homebrew/include", "-Wall", "-Wextra", "-fconstexpr-depth=2147483647", "-fconstexpr-loop-limit=2147483647", "-fconstexpr-ops-limit=2147483647"]
