name: Format & Deploy

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Format
        uses: DoozyX/clang-format-lint-action@v0.16.2
        with:
          source: '.'
          extensions: 'h,cpp,c'
          clangFormatVersion: 16
          inplace: True

  build:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install pip
        run: python -m pip install --upgrade pip
      - name: Install oj-verify-helper
        run: pip3 install online-judge-verify-helper
      - name: Verify code
        run: oj-verify run
      - name: Build docs
        run: oj-verify docs
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Setup Ruby
        run: |
          sudo apt install ruby-all-dev
          sudo apt install ruby-bundler
      - name: Build HTML
        run: |
          cd .verify-helper/markdown
          bundle install --path .vendor/bundle
          bundle exec jekyll build -I -d ../../_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
